import {
  array, bool, changed, describePaths, idempotencyHeader, int, listQuery, mutationQuery, object, okResult, operation,
  page, pageQuery, query, ref, scopeQuery, specInfo, specificationOperation, str, success, uploadPaths, usedSchemas, type Paths,
} from './openapi-common.js';

/** Complete JWT-session contract; API keys are never accepted for these operations. */
export function buildSessionOpenApiSpec(origin: string) {
  const admin = { role: 'admin' as const };
  const paths: Paths = {
    '/openapi.json': { get: specificationOperation() },
    '/config': { get: operation('Read public site configuration', ref('PublicConfig'), { public: true }) },
    '/avatar/{userId}': { get: operation('Download a public avatar', str, { public: true, binary: 'application/octet-stream', parameters: [query('v', str, 'Avatar version from avatarUrl; cache-busting value.') ] }) },
    '/auth/login': { post: operation('Sign in and create a JWT session', ref('LoginResponse'), { public: true, request: 'LoginRequest',
      description: 'If enabled, supply a six-digit TOTP or a recovery code in totp. A 401 error.code=totp_required means retry login with that code. The session token is different from an hpcm_ API key. New sessions are guarded against concurrent password/2FA changes.' }) },
    '/auth/register': { post: operation('Register a user and create a session', ref('LoginResponse'), { public: true, request: 'RegisterRequest', status: 201,
      description: 'Subject to closed/invite/open registration policy and IP limits. Invite mode requires inviteCode.' }) },
    '/auth/me': { get: operation('Read the current session user', ref('SessionUser')) },
    '/auth/avatar': {
      post: operation('Upload a base64 avatar', ref('SessionUser'), { request: 'UploadAvatarRequest' }),
      delete: operation('Delete the current user avatar', ref('SessionUser')),
    },
    '/auth/password': { put: operation('Change password and replace the session', ref('LoginResponse'), { request: 'ChangePasswordRequest',
      description: 'Supply the current password. Changes password and credential epoch atomically, invalidates previous user JWTs, and returns a replacement JWT. Use the new token for subsequent calls.' }) },
    '/auth/2fa/setup': { post: operation('Begin TOTP enrollment', object({ secret: str, otpauthUri: str }),
      { description: 'Returns a sensitive enrollment secret and QR-compatible otpauth URI; this does not enable TOTP until /auth/2fa/enable succeeds.' }) },
    '/auth/2fa/enable': { post: operation('Verify TOTP and enable two-factor authentication', object({ recoveryCodes: array(str) }), { request: 'EnableTwoFactorRequest', status: 201,
      description: 'Supply the six-digit code for the current enrollment secret. Recovery codes are returned once; store securely. This route is available when totp_setup_required restricts other actions.' }) },
    '/auth/2fa/disable': { post: operation('Disable two-factor authentication', success, { request: 'DisableTwoFactorRequest',
      description: 'An enrolled account must supply its current password or a valid TOTP code.' }) },
    '/auth/logout': { post: operation('Revoke the current session', success) },
    '/domains': { get: operation('List configured domains visible to this user', array(str), { description: 'Returns data as an array, unlike /v1/domains data.domains. Ordinary users see only public domains. Adding/managing domains requires administrator settings; claiming an address is a separate operation.' }) },
    '/mailboxes': {
      get: operation('List caller-owned mailboxes', array(ref('Mailbox')), { parameters: [query('all', { type: 'string', enum: ['1', 'true', '0', 'false'] }, 'Administrator all=1 or true includes all owners; ordinary users cannot request this range.')] }),
      post: operation('Claim an address on a configured domain', ref('Mailbox'), { request: 'ClaimMailboxRequest', status: 201,
        description: 'Claim only a domain returned by /domains. Existing history at the address becomes visible to the claimant. Ordinary users obey public/reserved-prefix/global/per-domain quotas. Does not provision a domain or Email Routing.' }),
    },
    '/mailboxes/shared': { get: operation('List inboxes shared with the caller', array(ref('SharedMailbox')), { description: 'Read-only inbound access; no sending, deletion or owner notifications. Read state is shared between mailbox readers.' }) },
    '/mailboxes/availability': { get: operation('Check mailbox availability', ref('MailboxAvailability'), { parameters: [query('localPart', str, undefined, true), query('domain', str, undefined, true)],
      description: 'Advisory only. Claim still enforces current domain visibility, ownership and quotas.' }) },
    '/mailboxes/{id}': {
      put: operation('Set mailbox display name', ref('Mailbox'), { request: 'UpdateMailboxRequest', description: 'Mailbox owner or administrator only.' }),
      delete: operation('Release mailbox ownership', object({ success: bool, deletedMessages: int }), { parameters: [query('deleteHistory', { type: 'string', enum: ['1', 'true', '0', 'false'] })],
        description: 'Default retains all address history for the next claimant. deleteHistory=1 atomically removes all existing address mail and ownership. Owner or administrator only. Previously delivered external links retain their promised 90-day validity.' }),
    },
    '/messages': { get: operation('List mail with cursor pagination', ref('MessagePage'), { parameters: listQuery }) },
    '/messages/send': { post: operation('Send, reply, resend or forward mail', ref('MessageSummary'), { request: 'SendMailRequest', status: 201, parameters: [idempotencyHeader],
      description: 'HTTP 201 may contain partial or total delivery failure. Inspect status/errorDetail/recipientOutcomes; retry only failed recipients. sent means provider acceptance, not confirmed destination-inbox delivery. Use base64 attachments or draft attachmentTokens; source forwarding attachments count toward the total. Large external attachments become independent 90-day signed links.' }) },
    '/messages/read': { post: operation('Mark selected messages read/unread', changed, { request: 'MarkReadRequest', parameters: mutationQuery }) },
    '/messages/read-all': { post: operation('Mark all visible incoming messages read', changed, { parameters: mutationQuery, request: 'MutationScopeRequest', requestRequired: false }) },
    '/messages/delete': { post: operation('Move selected messages to trash', object({ deleted: int }), { request: 'MessageIdsRequest', parameters: mutationQuery,
      description: 'Soft deletion. Restore before permanent deletion or the seven-day trash cleanup. Shared readers cannot delete mail.' }) },
    '/messages/restore': { post: operation('Restore selected trashed messages', object({ restored: int, changed: int }), { request: 'MessageIdsRequest', parameters: mutationQuery }) },
    '/messages/purge': { post: operation('Permanently delete selected trashed messages', object({ purged: int, changed: int }), { request: 'MessageIdsRequest', parameters: mutationQuery,
      description: 'Irreversible metadata removal. R2 cleanup failures are retried durably. Count reflects actual permitted deletions, not the input id count.' }) },
    '/messages/star': { post: operation('Set per-user stars', changed, { request: 'StarMessagesRequest', parameters: mutationQuery }) },
    '/messages/unread-count': { get: operation('Count unread inbox messages', object({ unread: int })) },
    '/messages/contacts': { get: operation('Read recent contact addresses', object({ contacts: array(str) }), { parameters: scopeQuery }) },
    '/messages/{id}': { get: operation('Read full message detail', ref('MessageDetail'), { parameters: scopeQuery,
      description: 'replyTo supplies preferred reply targets; fall back to fromAddress. Attachment URLs are short-lived signed URLs. Degraded mail has errorDetail; hasRaw reports archive availability.' }) },
    '/messages/{id}/thread': { get: operation('Read a visible thread', object({ items: array(ref('MessageSummary')) }), { parameters: scopeQuery }) },
    '/messages/{id}/raw': { get: operation('Download the original .eml', str, { binary: 'message/rfc822', parameters: scopeQuery,
      description: 'Binary response without a data envelope; 404 when the message has no original archive.' }) },
    '/attachments/{id}': { get: operation('Download an attachment by session or signed URL', str, { binary: 'application/octet-stream',
      parameters: [query('exp', { type: 'integer' }, 'Signed expiry, required together with sig for anonymous downloads.'), query('sig', str, 'HMAC signature; obtain the complete URL from message detail or an external email.')],
      security: [{ sessionToken: [] }, { attachmentSignature: [], attachmentExpiry: [] }],
      description: 'JWT mode enforces visibility. Signed mode requires both exp and sig and may serve retained external links after sent-mail deletion. Returns binary bytes with safe MIME/download headers.' }) },
    ...uploadPaths(),
    '/me/notify-prefs': {
      get: operation('Read masked personal notification and forwarding preferences', ref('NotifyPrefs')),
      put: operation('Update personal notification and forwarding preferences', ref('NotifyPrefs'), { request: 'UpdateNotifyPrefsRequest',
        description: 'At least one channel. ****** preserves stored secrets; explicit empty strings clear them. Enabled channels require complete valid configuration. Webhook is HPC Mail JSON, not a native Bark/ntfy request. Email forwarding includes rate limits; shared readers never receive owner notifications.' }),
    },
    '/me/notify-prefs/health': { get: operation('Read personal recent delivery health and forwarding quotas', ref('NotificationHealth'),
      { description: 'Current user only. pending/processing are queued; unknown means a result was not confirmed and must be checked before manual retry. Forward counts are attempts, and reset at UTC midnight. No message bodies or raw endpoint secrets are returned.' }) },
    '/me/notify-prefs/jobs/{id}/retry': { post: operation('Explicitly retry a failed or unknown personal notification', okResult,
      { description: 'Owner-only failed/unknown mail notification jobs. Check actual receipt before retrying unknown results to avoid a duplicate. Forward/test records cannot use this endpoint. The selected channel must be enabled. Webhook has no automatic retry; this action is explicit.' }) },
    '/me/notify-prefs/feishu-test': { post: operation('Send a real Feishu test with saved settings', okResult, { description: 'Performs an external notification and records its validated result. Failed delivery returns an error; this is not a dry run.' }) },
    '/me/notify-prefs/pushdeer-test': { post: operation('Send a real PushDeer test with saved settings', okResult, { description: 'Performs an external notification and validates HTTP and provider JSON success. This is not a dry run.' }) },
    '/api-keys': {
      get: operation('List own API keys without plaintext secrets', array(ref('ApiKeySummary'))),
      post: operation('Create an API key', ref('CreatedApiKey'), { request: 'CreateApiKeyRequest', status: 201,
        description: 'The full key is returned only once. Scopes limit /v1 operations, never grant administrator/JWT-only permissions, and are additionally bounded by the owner role and mailbox visibility.' }),
    },
    '/api-keys/{id}': {
      get: operation('Read own API key metadata', ref('ApiKeySummary')),
      put: operation('Update own API key limits/scopes/status', ref('ApiKeySummary'), { request: 'UpdateApiKeyRequest' }),
      delete: operation('Revoke own API key', success),
    },
    '/api-keys/{id}/logs': { get: operation('Read own API key audit logs', page(ref('ApiRequestLog')), { parameters: pageQuery }) },
    '/admin/users': {
      get: operation('List users', array(ref('AdminUser')), admin),
      post: operation('Create a user', ref('AdminUser'), { ...admin, request: 'CreateUserRequest', status: 201 }),
    },
    '/admin/users/{id}': {
      put: operation('Change user role/status or reset password', ref('AdminUser'), { ...admin, request: 'UpdateUserRequest',
        description: 'At least one field. Cannot disable self or remove the last active administrator. Password reset/disable revokes prior JWT epochs. Downgrading an administrator revokes their mailbox shares.' }),
      delete: operation('Delete a user', success, { ...admin, description: 'Cannot delete self or last active administrator. Releases owned mailboxes and revokes keys/shares; message history remains address-owned and may be inherited by later claimants.' }),
    },
    '/admin/mailboxes/{id}/transfer': { post: operation('Transfer any existing mailbox to an active user', ref('MailboxTransferResult'), {
      ...admin, request: 'TransferMailboxRequest', description: 'Administrator JWT only. userId is the target owner; expectedOwnerId comes from GET /mailboxes?all=1. Transfers an existing mailbox directly, including another user’s mailbox. Bypasses ordinary claim quotas, reserved prefixes and domain visibility. Preserves mailbox id, address, display name and all message/attachment history. Atomically changes ownership, revokes all old shares and records mailbox.transfer audit. A stale owner returns 409, unless the mailbox already belongs to the target: that retry returns transferred=false and does not revoke new shares. Disabled/missing users cannot receive a mailbox. Future mail uses the new owner’s notification preferences; existing receipt-time snapshots/jobs remain unchanged.'
    }) },
    '/admin/settings': {
      get: operation('Read current settings and domain revision', ref('Settings'), admin),
      put: operation('Update validated settings with domain conflict protection', ref('Settings'), { ...admin, request: 'UpdateSettingsRequest',
        description: 'Use expectedDomainsRevision from the latest GET when replacing domains. A stale revision returns 409. Domain changes control new claims; DNS/catch-all setup is external and existing owned mailbox routing persists.' }),
    },
    '/admin/settings/domain-status': { get: operation('Check public domain DNS onboarding', ref('DomainStatus'), { ...admin, parameters: [query('domain', str, undefined, true)],
      description: 'Checks MX/SPF via public DNS. Cannot prove the private Cloudflare catch-all target or end-to-end email delivery.' }) },
    '/admin/mailbox-shares': {
      get: operation('List grants on this administrator’s mailboxes', array(ref('MailboxShareGrant')), admin),
      put: operation('Replace grants on an owned mailbox', ref('MailboxShareGrant'), { ...admin, request: 'ReplaceMailboxSharesRequest',
        description: 'Only this administrator’s own mailboxes may be shared. Empty userIds revokes all shares. New grantees must be active ordinary users. Grants are read-only incoming mail; disable/downgrade changes remove effective access.' }),
    },
    '/admin/mailbox-shares/{mailboxId}/grantees/{userId}': { delete: operation('Revoke one mailbox grantee', success, admin) },
    '/admin/invites': {
      get: operation('List invitation codes and use history', array(ref('Invite')), admin),
      post: operation('Create invitation codes', array(ref('Invite')), { ...admin, request: 'CreateInviteRequest', status: 201 }),
    },
    '/admin/invites/{id}': { delete: operation('Revoke an invitation code', success, admin) },
    '/admin/api-keys': { get: operation('List all API key metadata with owners', array(ref('ApiKeySummary')), admin) },
    '/admin/api-keys/{id}': {
      get: operation('Read any API key metadata', ref('ApiKeySummary'), admin),
      delete: operation('Revoke any API key', success, admin),
    },
    '/admin/api-keys/{id}/logs': { get: operation('Read any API key audit logs', page(ref('ApiRequestLog')), { ...admin, parameters: pageQuery }) },
    '/admin/audit-logs': { get: operation('Read administrator audit logs', page(ref('AdminAuditLog')), { ...admin, parameters: pageQuery }) },
  };
  return { openapi: '3.1.0', info: specInfo('HPC Mail Session and Administration API',
    'JWT session API for all web-client functions. Authorization: Bearer <JWT> from login/register. hpcm_ API keys cannot authenticate these routes; see the related /v1 specification. Administrator endpoints require an active admin role. If site policy requires 2FA, un-enrolled sessions receive 403 totp_setup_required; /auth/me, logout and /auth/2fa routes remain available to complete setup.'),
    servers: [{ url: `${origin}/api` }], security: [{ sessionToken: [] }],
    externalDocs: { description: 'Agent usage guide and workflows', url: `${origin}/skill.md` },
    'x-relatedApis': [{ url: `${origin}/v1/openapi.json`, description: 'Scoped API-key mail/mailbox automation' }],
    tags: [{ name: 'Mail', description: 'Session, mail, mailbox and personal preferences' }, { name: 'Administration', description: 'Administrator role required; no API-key scopes grant this role.' }],
    components: { securitySchemes: {
      sessionToken: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      attachmentSignature: { type: 'apiKey', in: 'query', name: 'sig' }, attachmentExpiry: { type: 'apiKey', in: 'query', name: 'exp' },
    }, schemas: usedSchemas(paths) }, paths: describePaths(paths, 'jwt_'),
  };
}
